[project]
name = "ai-agent-creation-with-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.2.15",
    "langchain-openai>=1.1.12",
    "langfuse>=3.0.0,<4.0.0",
    "pandas>=3.0.2",
    "python-dotenv>=1.2.2",
    "ulid-py>=1.1.0",
]
